AWS_ACCESS_KEY_ID = ENV.fetch('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = ENV.fetch('AWS_SECRET_ACCESS_KEY')

AWS_S3_BUCKET_REGION = ENV.fetch('AWS_S3_BUCKET_REGION')
AWS_S3_BUCKET_NAME = ENV.fetch('AWS_S3_BUCKET_NAME')

AWS_SQS_QUEUE_URL = ENV.fetch('AWS_SQS_QUEUE_URL')

Aws.config.update(
  credentials: Aws::Credentials.new(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY),
  region: AWS_S3_BUCKET_REGION
)
